### ISSUE TITLE
Calculated score does not account for weights

### ISSUE THREAD

**Issue by ms609** [mbrazeau/MorphyLib#14] opened 2017-05-27 06:40 UTC
Minimal steps to reproduce:
A test case containing the first two characters from Thomas's test cases
Tree: `((((((1,2),3),4),5),6),(7,(8,(9,(10,(11,12))))));`
First character: `23--1??--032`
Second character: `1---1111---1`

Here's some pseudo-c code - I'm working in R but you should be able to follow.  I've given the C numberings for the characters (= R numberings minus one).

```c
morphyObj = mpl_new_Morphy();
mpl_init_Morphy(12, 2, morphyObj);
mpl_attach_rawdata("213-----11?1?1-1--0-3-21;", morphyObj);
mpl_set_num_internal_nodes(12, morphyObj);
mpl_set_parsim_t(0, 'FITCH', morphyObj);  
mpl_set_parsim_t(1, 'FITCH', morphyObj);
mpl_set_charac_weight(0, 1, morphyObj);
mpl_set_charac_weight(1, 2, morphyObj); // If weight is set to 1 then the correct score, 7, is returned
mpl_apply_tipdata(morphyObj);
```
... and then the code in [RMorphy.C](https://github.com/ms609/inapplicable/blob/MorphyLib/src/RMorphy.c)

Expected result = 5 + (2 × 2) = 9
Actual result (**edit** and result if weights are set to one apiece) = 5 + 2 = 7

**Comment by mbrazeau** [comment] 2017-05-27 10:57
Good to know. I'll build a test case for this one and see what happens in the MorphyLib test suite and get back to you. However, is the correct result being returned with unweighted characters?

**Comment by mbrazeau** [comment] 2017-05-27 10:59
Oh. I know what the problem is. I stupidly did not apply weighting to the inapplicable functions.... derp! derp! derp!

**Comment by mbrazeau** [comment] 2017-05-27 11:03
Fix applied and merged to master.

**Comment by mbrazeau** [comment] 2017-05-27 11:22
I've also updated wagner, but didn't yet merge it to master because the Wagner functions aren't fully working yet.

**Comment by ms609** [comment] 2017-05-27 15:29
Working for me too! Great stuff (-:

**Comment by mbrazeau** [comment] 2017-05-27 16:05
Great. Thanks for the report.

**Closed by mbrazeau** 2017-05-27 16:05 UTC
